### ISSUE TITLE
能不能出一个戒撸的版本

### ISSUE THREAD

**Issue by ctfrookie** [SamuNatsu/nonebot-plugin-deer-pipe#18]
![f73cd1b13be8231c29b22a377fb56000](https://github.com/user-attachments/assets/8874f864-842e-4dc6-af24-bf3dd2def6f7)

**Comment by SamuNatsu** [comment]
![tmp](https://github.com/user-attachments/assets/f14214b4-41bb-498c-b40f-08974fd859ed)

**Comment by SamuNatsu** [comment]
![tmp](https://github.com/user-attachments/assets/bf6514dc-7e85-49ae-916c-595e237a24a0)
