### ISSUE TITLE
个别群员🦌不了

### ISSUE THREAD

**Issue by xANoyU** [SamuNatsu/nonebot-plugin-deer-pipe#19]
这个是相关报错 求助

[报错.log](https://github.com/user-attachments/files/18061732/default.log)

**Comment by SamuNatsu** [comment]
数据库相比上版本有破坏性更新，可以删掉数据库文件再试一下

**Comment by xANoyU** [comment]
> 数据库相比上版本有破坏性更新，可以删掉数据库文件再试一下

数据库文件在哪里(

**Comment by xANoyU** [comment]
弄好了 编辑了一下数据
🦌不了的群员avatar_data是空的, 要删除掉这个群员的记录让他重新🦌才能生成头像数据
可能是第一次记录数据的时候获取头像数据失败了
![image](https://github.com/user-attachments/assets/14ec1238-1241-4abb-9f52-1fc301a31b87)
