### ISSUE TITLE
[功能建议]增加补签功能

### ISSUE THREAD

**Issue by enKl03B** [SamuNatsu/nonebot-plugin-deer-pipe#4]
如题，最好能选择具体日期（  
谢谢大佬

**Comment by SamuNatsu** [comment]
补签功能真的那么重要吗（难视）

少🦌怡情，大🦌上身

**Comment by enKl03B** [comment]
> 补签功能真的那么重要吗（难视）
> 
> 少🦌怡情，大🦌上身

~~做一个吧，大家什么都会做的~~

**Comment by SamuNatsu** [comment]
v0.3.2 版本已实现补🦌功能

请前往 Release 查看相关更改
