### ISSUE TITLE
建议增加当日多次签到功能

### ISSUE THREAD

**Issue by Blokura** [SamuNatsu/nonebot-plugin-deer-pipe#5]
如题，个人认为单纯的签到可以是一日限制一次
但是根据群友反应🦌签到可以多次
![qq_pic_merged_1723966891313](https://github.com/user-attachments/assets/5d89125b-3c2d-4c33-8903-17273b8342bb)

**Comment by SamuNatsu** [comment]
一直没有想好如何展示“一日多🦌”的情况

而且目前数据库对于🦌的记录是使用31长度整数位运算，如果要改一日多次将会发生重大数据库修改

**Comment by SamuNatsu** [comment]
v0.3.0 已支持一日多🦌

请根据 Release 信息自行尝试迁移数据库
