### ISSUE TITLE
添加黑名单功能

### ISSUE THREAD

**Issue by 050644zf** [SamuNatsu/nonebot-plugin-deer-pipe#7]
就像[这个](https://github.com/mengshouer/nonebot_plugin_analysis_bilibili/pull/9)

**Comment by SherkeyXD** [comment]
干脆用群管插件得了（
比如 [这个](https://github.com/cubstaryow/nonebot-plugin-authrespond)

**Comment by 050644zf** [comment]
> 干脆用群管插件得了（
> 比如 [这个](https://github.com/cubstaryow/nonebot-plugin-authrespond)

测试无效
![Screenshot_2024-08-25-14-35-53-811_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/5c72d038-ee0d-4177-a5ac-b0e25e15b3d7)

**Comment by SherkeyXD** [comment]
> 测试无效
> ![Screenshot_2024-08-25-14-35-53-811_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/5c72d038-ee0d-4177-a5ac-b0e25e15b3d7)
> 

superuser会被bypass，得让群友测（x

**Comment by 050644zf** [comment]
> > 测试无效
> > ![Screenshot_2024-08-25-14-35-53-811_com.tencent.mobileqq-edit.jpg](https://github.com/user-attachments/assets/5c72d038-ee0d-4177-a5ac-b0e25e15b3d7)
> > 
> 
> superuser会被bypass，得让群友测（x
> 
> 

还有这种，懂了谢谢
